---
replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "analytical-platform-dashboard-service"

podAnnotations: {}
podLabels: {}
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "default"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-http01
  hosts:
    - host: dashboards.development.analytical-platform.service.justice.gov.uk
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: dashboard-service-tls
      hosts:
        - dashboards.development.analytical-platform.service.justice.gov.uk

affinity: {}
nodeSelector: {}
tolerations: []

app:
  image:
    repository: ghcr.io/ministryofjustice/analytical-platform-ui
    pullPolicy: IfNotPresent
    tag: ""
  environment:
    # TODO this needs to be specified for each environment
    - name: APP_ENV
      value: development
    - name: DJANGO_SETTINGS_MODULE
      value: ap.settings.development
    - name: SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: dashboard-service-app-secrets
          key: secret-key
    - name: SENTRY_DSN
      valueFrom:
        secretKeyRef:
          name: dashboard-service-app-secrets
          key: sentry-dsn
    - name: AUTH0_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: dashboard-service-app-secrets
          key: auth0-client-id
    - name: AUTH0_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dashboard-service-app-secrets
          key: auth0-client-secret
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: dashboard-service-rds
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dashboard-service-rds
          key: password
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: dashboard-service-rds
          key: address
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: dashboard-service-rds
          key: port
    - name: DB_NAME
      value: "dashboard_service"
  port: 8000
  # These are removed while healthcheck endpoint is worked on
  livenessProbe:
    httpGet:
      path: /healthcheck/
      port: app
      initialDelaySeconds: 30
  readinessProbe:
    httpGet:
      path: /healthcheck/
      port: app
      initialDelaySeconds: 30
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  securityContext:
    capabilities:
      drop:
        - ALL
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
