# Generated by Django 5.2.1 on 2025-07-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth0_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="external_provider_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
