---
version: "3.8"

services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: dashboard_service
      POSTGRES_PASSWORD: dashboard_service
      POSTGRES_DB: dashboard_service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ap"]
      interval: 5s
      timeout: 5s
      retries: 5
