---
name: 🗺️ Chart Lint

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  chart-lint:
    name: Chart Lint
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-chart-lint.yml@bc0d450d55cc014693437d793b797b7b0e281db4 # v7.3.1
